language: python
dist: trusty
sudo: false
cache:
  pip: true

python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements-test.txt
script:
  - pytest -v --cov-report term-missing --cov=pd2ppt
